rabbit_mq:
    # Status URL:  http://rabbit0002:RbIEJfCuMc@ec2-67-202-42-147.compute-1.amazonaws.com:30002/
    user: rabbit0002
    pass: RbIEJfCuMc
    host: ec2-67-202-42-147.compute-1.amazonaws.com
    port: 15002
    vhost: /rabbit0002
    logging: false
    socialq: socialq # Where we publish the Social Q messages
    agentq: agentq # Where agent requests to take a call get passed
    callq: callq
    responseq: responseq

twitter:
    username: squirrelrific
    password: squirrelsrock
    keywords: 
        - fail
        - sucks
        - bad
    klout_key: txqh6gfjgwmb6tytv7yvb54y

sinatra:
    port: 4567

agents:
    - name: John Doe
      uname: jdoe
      phone_number: '+14157044517'
    - name: Jane Smith
      uname: jsmith
      phone_number: '+14153675082'
      
users:
    - name: Lenos Squirrel
      phone_number: '+14157044517'
      twitter_user: LenosSquirrel
    - name:
      phone_number:
      twitter_user:
    - name:
      phone_number:
      twitter_user:


weight_rules:
    phone: 10 # Arrived as a realtime phone request
    tweet: 8 # Arrived as a tweet
    influence: 2 # Factor by which social influence should weight, in this case (social influence * X ), may be a float
    keyword: 5 # If a keyword is spotted in the tweet stream of the user while in session, add X to the weight