amazon:
    aws_access_key: 0YSG6K5HPC0KAJHSMPG2
    aws_secret_access_key: R3jcbuwc26wQnUBNQPkaYY53BJu7vGI72w7+phm2
    endpoint: http://queue.amazonaws.com
    session_sqs: sessions
    agent_sqs: agents

twitter:
    username: squirrelrific
    password: squirrelsrock
    keywords: squirrelrific

sinatra:
    port: 4567

agents:
    - name: John Doe
      uname: jdoe
      phone: +14157044517
    - name: Jane Smith
      uname: jsmith
      phone: +14153675082
      
users:
    - name: Lenos Squirrel
      phone: +14157044517
      twitter_user: LenosSquirrel
    - name:
      phone:
      twitter_user:
    - name:
      phone:
      twitter_user:

queue:
    timer: 1
