amazon:
    aws_access_key: 0YSG6K5HPC0KAJHSMPG2
    aws_secret_access_key: R3jcbuwc26wQnUBNQPkaYY53BJu7vGI72w7+phm2
    call_queue:
    agent_queue:

twitter:
    username: squirrelrific
    password: squirrelsrock
    keywords: squirrelrific

sinatra:
    port: 4567

agents:
    - name: John Doe
      phone: +14157044517
    - name: Jane Smith
      phone: +14153675082
      
users:
    - name:
      phone:
      twitter_user:
    - name:
      phone:
      twitter_user:
    - name:
      phone:
      twitter_user:

queue:
    timer: 1
