rabbit_mq:
    # Status URL:  http://rabbit0002:RbIEJfCuMc@us-east-1.beta.srs.cloud.rabbitmq.com:30002/
    user: rabbit0002
    pass: RbIEJfCuMc
    host: us-east-1.beta.srs.cloud.rabbitmq.com
    port: 15002
    vhost: /rabbit0002
    logging: false
    socialq: socialq # Where we publish the Social Q messages
    dumpq: dumpq # Used to send a replication of the socialq so we may easily capture scenarios generated, comment out to stop
    agentq: agentq # Where agent requests to take a call get passed
    callq: callq
    responseq: responseq

tropo:
    # &queue_name=1234&request_type=session_api&queue_name='1234'&phone_number=14153675082
    url: 'http://api.tropo.com/1.0/sessions?action=create&token=38473194d4e8c346b818ac1ca42aa06b9eb0558a764ed2e90a483758c8fe01534bc7d6755a728772f1cbdde2'
twitter:
    username: squirrelrific
    password: squirrelsrock
    keywords: 
        - fail
        - sucks
        - bad
    klout_key: txqh6gfjgwmb6tytv7yvb54y

sinatra:
    #port: 10917
    port: 4567

agents:
    - name: John Doe
      uname: jdoe
      phone_number: '14153675082'
    - name: Jane Smith
      uname: jsmith
      phone_number: '14153675082'
      
users:
    - name: Lenos Squirrel
      phone_number: '9166002497'
      twitter_user: LenosSquirrel
    - name: Squirrelrific
      phone_number: '3055195825'
      twitter_user: squirrelrific
    - name: Heidi Squirrel
      phone_number: jsgoecke
      twitter_user: heidi_squirrel

weight_rules:
    phone: 10 # Arrived as a realtime phone request
    tweet: 8 # Arrived as a tweet
    influence: 2 # Factor by which social influence should weight, in this case (social influence * X ), may be a float
    keyword: 5 # If a keyword is spotted in the tweet stream of the user while in session, add X to the weight